### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'meta'

### ISSUE THREAD

**Issue by alafanechere** [mbriliauskas/scrapy-rabbitmq-link#1]
Hello,
I wanted to try your implementation of scrapy-rabbitmq but when I launch my spider I encounter this error... Do you know where this comes from ? I have quite a lot of trouble to debug it...
I use Python 2.7

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/downloader/__init__.py", line 98, in fetch
    dfd = self.middleware.download(self._enqueue_request, request, spider)
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 74, in download
    deferred = mustbe_deferred(process_request, request)
  File "/usr/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/usr/local/lib/python2.7/site-packages/scrapy/downloadermiddlewares/downloadtimeout.py", line 26, in process_request
    request.meta.setdefault('download_timeout', self._timeout)
exceptions.AttributeError: 'generator' object has no attribute 'meta'
```

**Comment by mbriliauskas** [comment]
Good morning Augustin,
thank you for pointing that out, I tested and updated the example spider code at readme.
Please let me know if you still experience an issue.

**Comment by alafanechere** [comment]
Thanks Mantas its works perfectly !
Do you plan on working on adding more content to messages body in order to pass request meta to the spider ?
