### ISSUE TITLE
AttributeError: type object 'Scheduler' has no attribute 'from_crawler'

### ISSUE THREAD

**Issue by rubberviscous** [mbriliauskas/scrapy-rabbitmq-link#4]
I'm seeing the following error after configuring everything according to the readme. I'm using Scrapy 1.4.0. 

`Traceback (most recent call last):
  File "/Users/jdoe/Documents/Projects/helloworld/scraper/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/Users/jdoe/Documents/Projects/helloworld/scraper/lib/python2.7/site-packages/scrapy/crawler.py", line 95, in crawl
    six.reraise(*exc_info)
  File "/Users/jdoe/Documents/Projects/helloworld/scraper/lib/python2.7/site-packages/scrapy/crawler.py", line 79, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
AttributeError: type object 'Scheduler' has no attribute 'from_crawler'`

**Comment by mbriliauskas** [comment]
Thank you for the reporting, I did not test it with Scrapy 1.4.0. Appears the "from_crawler" method became mandatory.

I will try to fix this in a week.

**Comment by mbriliauskas** [comment]
I made changes to the project and tested it with Scrapy==1.4.0. The plugin became lighter to use in spider, also I refactored the code and pushed it to pypi. Feel free to use `pip install scrapy-rabbitmq-link` for installation.

Please let me know if you still experience the issue.

**Comment by rubberviscous** [comment]
Thank! I will test it out and let you know.

**Comment by HrTran** [comment]
Hi, I got the same problem with Scrapy 1.5.0 and Twisted 18.4.0. I have downgraded to Scrapy 1.4.0, and still stuck at it
```
2018-05-15 00:14:09 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/hembit/pyenv/lib/python3.5/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/hembit/pyenv/lib/python3.5/site-packages/scrapy/crawler.py", line 79, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
AttributeError: type object 'Scheduler' has no attribute 'from_crawler'
```
